// ==========================================
// FoodResQ AI — Comprehensive Demo Data
// ==========================================

import type {
  Donation,
  Delivery,
  User,
  Notification,
  AnalyticsData,
  Testimonial,
  DashboardStats,
  Coordinates,
} from '@/lib/types';

// === DEMO USERS ===
export const demoUsers: User[] = [
  {
    id: 'donor-1',
    name: 'Rajesh Sharma',
    email: 'rajesh@tajhotel.com',
    phone: '+919876543210',
    role: 'donor',
    organization: 'Taj Palace Hotel',
    address: 'Connaught Place, New Delhi',
    coordinates: { lat: 28.6315, lng: 77.2167 },
    verified: true,
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date(),
  },
  {
    id: 'donor-2',
    name: 'Priya Patel',
    email: 'priya@marriott.com',
    phone: '+919876543211',
    role: 'donor',
    organization: 'Marriott Banquet',
    address: 'Aerocity, New Delhi',
    coordinates: { lat: 28.5562, lng: 77.0937 },
    verified: true,
    createdAt: new Date('2025-02-20'),
    updatedAt: new Date(),
  },
  {
    id: 'donor-3',
    name: 'Amit Kumar',
    email: 'amit@canteen.com',
    phone: '+919876543212',
    role: 'donor',
    organization: 'IIT Delhi Canteen',
    address: 'IIT Delhi, Hauz Khas',
    coordinates: { lat: 28.5459, lng: 77.1926 },
    verified: true,
    createdAt: new Date('2025-03-10'),
    updatedAt: new Date(),
  },
  {
    id: 'ngo-1',
    name: 'Sunita Devi',
    email: 'sunita@feedingindia.org',
    phone: '+919876543220',
    role: 'ngo',
    organization: 'Feeding India Foundation',
    address: 'Sarojini Nagar, New Delhi',
    coordinates: { lat: 28.5747, lng: 77.2003 },
    verified: true,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date(),
  },
  {
    id: 'ngo-2',
    name: 'Mohammad Ali',
    email: 'ali@robinhood.org',
    phone: '+919876543221',
    role: 'ngo',
    organization: 'Robin Hood Army',
    address: 'Nizamuddin, New Delhi',
    coordinates: { lat: 28.5921, lng: 77.2434 },
    verified: true,
    createdAt: new Date('2024-08-15'),
    updatedAt: new Date(),
  },
  {
    id: 'ngo-3',
    name: 'Kavitha Menon',
    email: 'kavitha@annadan.org',
    phone: '+919876543222',
    role: 'ngo',
    organization: 'Annadan Trust',
    address: 'Lajpat Nagar, New Delhi',
    coordinates: { lat: 28.5677, lng: 77.2375 },
    verified: true,
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date(),
  },
  {
    id: 'rider-1',
    name: 'Vikram Singh',
    phone: '+919876543230',
    role: 'delivery',
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'rider-2',
    name: 'Deepak Yadav',
    phone: '+919876543231',
    role: 'delivery',
    verified: true,
    createdAt: new Date('2025-02-01'),
    updatedAt: new Date(),
  },
  {
    id: 'rider-3',
    name: 'Sanjay Mehra',
    phone: '+919876543232',
    role: 'delivery',
    verified: true,
    createdAt: new Date('2025-03-01'),
    updatedAt: new Date(),
  },
  {
    id: 'admin-1',
    name: 'Admin User',
    email: 'admin@foodresq.ai',
    phone: '+919876543200',
    role: 'admin',
    organization: 'FoodResQ AI',
    verified: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
];

// === DEMO DONATIONS ===
export const demoDonations: Donation[] = [
  {
    id: 'don-1',
    donorId: 'donor-1',
    donorName: 'Rajesh Sharma',
    donorOrg: 'Taj Palace Hotel',
    foodName: 'Vegetable Biryani',
    description: 'Fresh vegetable biryani from lunch buffet',
    quantity: 25,
    unit: 'plates',
    vegType: 'veg',
    expiryTime: new Date(Date.now() + 45 * 60000),
    urgencyLevel: 'high',
    imageUrl: '/demo/biryani.jpg',
    tags: ['indian', 'rice', 'biryani', 'lunch'],
    pickupAddress: 'Taj Palace Hotel, Connaught Place',
    coordinates: { lat: 28.6315, lng: 77.2167 },
    status: 'matched',
    matchedNgoId: 'ngo-1',
    matchedNgoName: 'Feeding India Foundation',
    riderId: 'rider-1',
    riderName: 'Vikram Singh',
    aiAnalysis: {
      foodType: 'Vegetable Biryani',
      estimatedQuantity: '25 plates',
      vegClassification: 'veg',
      urgencyEstimate: 'high',
      freshness: 'Fresh — 45 minutes remaining',
      tags: ['indian', 'rice', 'biryani', 'spicy'],
      confidence: 94,
      summary: '25 plates of fresh vegetable biryani. High urgency.',
    },
    createdAt: new Date(Date.now() - 30 * 60000),
    updatedAt: new Date(),
  },
  {
    id: 'don-2',
    donorId: 'donor-2',
    donorName: 'Priya Patel',
    donorOrg: 'Marriott Banquet',
    foodName: 'Paneer Butter Masala + Naan',
    description: 'From wedding reception dinner',
    quantity: 50,
    unit: 'servings',
    vegType: 'veg',
    expiryTime: new Date(Date.now() + 120 * 60000),
    urgencyLevel: 'medium',
    tags: ['indian', 'paneer', 'curry', 'dinner', 'wedding'],
    pickupAddress: 'Marriott, Aerocity, New Delhi',
    coordinates: { lat: 28.5562, lng: 77.0937 },
    status: 'pending',
    createdAt: new Date(Date.now() - 15 * 60000),
    updatedAt: new Date(),
  },
  {
    id: 'don-3',
    donorId: 'donor-3',
    donorName: 'Amit Kumar',
    donorOrg: 'IIT Delhi Canteen',
    foodName: 'Rice & Dal Combo',
    description: 'Leftover from evening mess',
    quantity: 40,
    unit: 'portions',
    vegType: 'veg',
    expiryTime: new Date(Date.now() + 60 * 60000),
    urgencyLevel: 'high',
    tags: ['indian', 'rice', 'dal', 'wholesome'],
    pickupAddress: 'IIT Delhi Main Canteen, Hauz Khas',
    coordinates: { lat: 28.5459, lng: 77.1926 },
    status: 'accepted',
    matchedNgoId: 'ngo-2',
    matchedNgoName: 'Robin Hood Army',
    createdAt: new Date(Date.now() - 45 * 60000),
    updatedAt: new Date(),
  },
  {
    id: 'don-4',
    donorId: 'donor-1',
    donorName: 'Rajesh Sharma',
    donorOrg: 'Taj Palace Hotel',
    foodName: 'Mixed Sandwiches & Pastries',
    description: 'Corporate event leftovers',
    quantity: 35,
    unit: 'pieces',
    vegType: 'veg',
    expiryTime: new Date(Date.now() + 180 * 60000),
    urgencyLevel: 'low',
    tags: ['bakery', 'sandwiches', 'snacks'],
    pickupAddress: 'Taj Palace Hotel, Connaught Place',
    coordinates: { lat: 28.6315, lng: 77.2167 },
    status: 'pending',
    createdAt: new Date(Date.now() - 10 * 60000),
    updatedAt: new Date(),
  },
  {
    id: 'don-5',
    donorId: 'donor-2',
    donorName: 'Priya Patel',
    donorOrg: 'Marriott Banquet',
    foodName: 'Chicken Curry & Rice',
    description: 'From corporate lunch',
    quantity: 20,
    unit: 'plates',
    vegType: 'non-veg',
    expiryTime: new Date(Date.now() + 30 * 60000),
    urgencyLevel: 'critical',
    tags: ['indian', 'chicken', 'curry', 'rice'],
    pickupAddress: 'Marriott, Aerocity, New Delhi',
    coordinates: { lat: 28.5562, lng: 77.0937 },
    status: 'in-transit',
    matchedNgoId: 'ngo-3',
    matchedNgoName: 'Annadan Trust',
    riderId: 'rider-2',
    riderName: 'Deepak Yadav',
    createdAt: new Date(Date.now() - 60 * 60000),
    updatedAt: new Date(),
  },
  {
    id: 'don-6',
    donorId: 'donor-3',
    donorName: 'Amit Kumar',
    donorOrg: 'IIT Delhi Canteen',
    foodName: 'Idli Sambhar',
    description: 'Breakfast leftovers',
    quantity: 60,
    unit: 'plates',
    vegType: 'veg',
    expiryTime: new Date(Date.now() - 30 * 60000),
    urgencyLevel: 'low',
    tags: ['south indian', 'idli', 'breakfast'],
    pickupAddress: 'IIT Delhi Canteen',
    coordinates: { lat: 28.5459, lng: 77.1926 },
    status: 'delivered',
    matchedNgoId: 'ngo-1',
    matchedNgoName: 'Feeding India Foundation',
    riderId: 'rider-3',
    riderName: 'Sanjay Mehra',
    createdAt: new Date(Date.now() - 180 * 60000),
    updatedAt: new Date(Date.now() - 90 * 60000),
  },
];

// === DEMO DELIVERIES ===
export const demoDeliveries: Delivery[] = [
  {
    id: 'del-1',
    donationId: 'don-1',
    riderId: 'rider-1',
    riderName: 'Vikram Singh',
    donorId: 'donor-1',
    ngoId: 'ngo-1',
    pickupAddress: 'Taj Palace Hotel, Connaught Place',
    deliveryAddress: 'Feeding India, Sarojini Nagar',
    pickupCoords: { lat: 28.6315, lng: 77.2167 },
    deliveryCoords: { lat: 28.5747, lng: 77.2003 },
    status: 'en-route',
    estimatedTime: 18,
    distance: 4.2,
    otp: '4829',
    pickupVerified: true,
    deliveryVerified: false,
    startedAt: new Date(Date.now() - 20 * 60000),
    createdAt: new Date(Date.now() - 25 * 60000),
  },
  {
    id: 'del-2',
    donationId: 'don-5',
    riderId: 'rider-2',
    riderName: 'Deepak Yadav',
    donorId: 'donor-2',
    ngoId: 'ngo-3',
    pickupAddress: 'Marriott, Aerocity',
    deliveryAddress: 'Annadan Trust, Lajpat Nagar',
    pickupCoords: { lat: 28.5562, lng: 77.0937 },
    deliveryCoords: { lat: 28.5677, lng: 77.2375 },
    status: 'picked-up',
    estimatedTime: 35,
    distance: 12.5,
    otp: '7156',
    pickupVerified: true,
    deliveryVerified: false,
    startedAt: new Date(Date.now() - 10 * 60000),
    createdAt: new Date(Date.now() - 15 * 60000),
  },
  {
    id: 'del-3',
    donationId: 'don-6',
    riderId: 'rider-3',
    riderName: 'Sanjay Mehra',
    donorId: 'donor-3',
    ngoId: 'ngo-1',
    pickupAddress: 'IIT Delhi Canteen',
    deliveryAddress: 'Feeding India, Sarojini Nagar',
    pickupCoords: { lat: 28.5459, lng: 77.1926 },
    deliveryCoords: { lat: 28.5747, lng: 77.2003 },
    status: 'delivered',
    estimatedTime: 15,
    distance: 3.1,
    otp: '3894',
    pickupVerified: true,
    deliveryVerified: true,
    startedAt: new Date(Date.now() - 180 * 60000),
    completedAt: new Date(Date.now() - 150 * 60000),
    createdAt: new Date(Date.now() - 185 * 60000),
  },
];

// === DEMO NOTIFICATIONS ===
export const demoNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'donor-1',
    title: 'NGO Accepted Your Donation',
    message: 'Feeding India Foundation accepted your vegetable biryani donation.',
    type: 'donation',
    read: false,
    createdAt: new Date(Date.now() - 5 * 60000),
  },
  {
    id: 'notif-2',
    userId: 'donor-1',
    title: 'Rider Assigned',
    message: 'Vikram Singh has been assigned to pick up your donation.',
    type: 'delivery',
    read: false,
    createdAt: new Date(Date.now() - 10 * 60000),
  },
  {
    id: 'notif-3',
    userId: 'ngo-1',
    title: 'New Donation Nearby',
    message: '25 plates of biryani available at Taj Palace Hotel (2.1 km away)',
    type: 'donation',
    read: false,
    createdAt: new Date(Date.now() - 8 * 60000),
  },
  {
    id: 'notif-4',
    userId: 'rider-1',
    title: 'New Delivery Request',
    message: 'Pick up from Taj Palace Hotel → Feeding India Foundation (4.2 km)',
    type: 'delivery',
    read: true,
    createdAt: new Date(Date.now() - 25 * 60000),
  },
  {
    id: 'notif-5',
    userId: 'admin-1',
    title: '⚠️ Urgency Alert',
    message: 'Chicken curry at Marriott expires in 30 minutes. No rider assigned!',
    type: 'alert',
    read: false,
    createdAt: new Date(Date.now() - 2 * 60000),
  },
];

// === DEMO RIDER LOCATIONS ===
export const demoRiderLocations = [
  { riderId: 'rider-1', coordinates: { lat: 28.6100, lng: 77.2100 }, heading: 180, speed: 22, lastUpdated: new Date() },
  { riderId: 'rider-2', coordinates: { lat: 28.5600, lng: 77.1200 }, heading: 90, speed: 30, lastUpdated: new Date() },
  { riderId: 'rider-3', coordinates: { lat: 28.5650, lng: 77.1980 }, heading: 0, speed: 0, lastUpdated: new Date() },
];

// === DEMO ANALYTICS ===
export const demoAnalytics: AnalyticsData = {
  totalMealsSaved: 127845,
  totalDonations: 8432,
  activeDeliveries: 23,
  ngosConnected: 156,
  co2Reduced: 42.8,
  foodWasteReduced: 64200,
  avgDeliveryTime: 22,
  topDonors: [
    { name: 'Taj Palace Hotel', meals: 12450 },
    { name: 'Marriott Banquet', meals: 9870 },
    { name: 'IIT Delhi Canteen', meals: 8340 },
    { name: 'Oberoi Hotels', meals: 7230 },
    { name: 'YMCA Hostel', meals: 5670 },
  ],
  topNgos: [
    { name: 'Feeding India', received: 18920 },
    { name: 'Robin Hood Army', received: 15640 },
    { name: 'Annadan Trust', received: 12340 },
    { name: 'Akshaya Patra', received: 10560 },
    { name: 'Goonj', received: 8970 },
  ],
  dailyDonations: [
    { date: 'Mon', count: 145 },
    { date: 'Tue', count: 132 },
    { date: 'Wed', count: 168 },
    { date: 'Thu', count: 155 },
    { date: 'Fri', count: 189 },
    { date: 'Sat', count: 234 },
    { date: 'Sun', count: 198 },
  ],
  weeklyTrends: [
    { week: 'W1', donations: 890, deliveries: 845 },
    { week: 'W2', donations: 920, deliveries: 876 },
    { week: 'W3', donations: 1050, deliveries: 998 },
    { week: 'W4', donations: 1180, deliveries: 1134 },
  ],
};

// === DEMO TESTIMONIALS ===
export const demoTestimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Arjun Mehta',
    role: 'Head Chef',
    organization: 'Taj Palace Hotel',
    content: 'FoodResQ AI transformed how we handle surplus food. What used to be wasted now feeds hundreds of people daily. The AI detection is incredibly accurate.',
    avatar: '',
    rating: 5,
  },
  {
    id: '2',
    name: 'Meera Krishnan',
    role: 'Operations Head',
    organization: 'Feeding India Foundation',
    content: 'The realtime matching and live tracking has made our operations 10x more efficient. We can now rescue food before it expires, thanks to the urgency alerts.',
    avatar: '',
    rating: 5,
  },
  {
    id: '3',
    name: 'Vikram Singh',
    role: 'Volunteer Rider',
    organization: 'Independent',
    content: 'As a delivery volunteer, the route optimization and live navigation make my job so much easier. I can complete 8-10 deliveries a day now with the reward system keeping me motivated.',
    avatar: '',
    rating: 5,
  },
];

// === DEMO DASHBOARD STATS ===
export const demoDonorStats: DashboardStats[] = [
  { label: 'Meals Donated', value: 2450, icon: 'Utensils', color: '#a855f7', trend: 12 },
  { label: 'Food Saved (kg)', value: 1840, suffix: 'kg', icon: 'Package', color: '#06b6d4', trend: 8 },
  { label: 'CO₂ Reduced', value: 4.2, suffix: 'tons', icon: 'Leaf', color: '#10b981', trend: 15 },
  { label: 'Active Pickups', value: 3, icon: 'Truck', color: '#3b82f6' },
];

export const demoNgoStats: DashboardStats[] = [
  { label: 'Meals Received', value: 18920, icon: 'Heart', color: '#ec4899', trend: 18 },
  { label: 'Nearby Donations', value: 7, icon: 'MapPin', color: '#f97316' },
  { label: 'Avg Delivery Time', value: 22, suffix: 'min', icon: 'Clock', color: '#06b6d4' },
  { label: 'People Fed', value: 52400, icon: 'Users', color: '#a855f7', trend: 22 },
];

export const demoDeliveryStats: DashboardStats[] = [
  { label: 'Deliveries Done', value: 342, icon: 'CheckCircle', color: '#10b981', trend: 10 },
  { label: 'Active Delivery', value: 1, icon: 'Navigation', color: '#3b82f6' },
  { label: 'Reward Points', value: 8450, icon: 'Award', color: '#f59e0b' },
  { label: 'Distance Covered', value: 1240, suffix: 'km', icon: 'Route', color: '#a855f7' },
];

export const demoAdminStats: DashboardStats[] = [
  { label: 'Total Meals Saved', value: 127845, icon: 'Utensils', color: '#a855f7', trend: 15 },
  { label: 'Active Deliveries', value: 23, icon: 'Truck', color: '#06b6d4' },
  { label: 'NGOs Connected', value: 156, icon: 'Heart', color: '#ec4899', trend: 8 },
  { label: 'CO₂ Reduced', value: 42.8, suffix: 'tons', icon: 'Leaf', color: '#10b981', trend: 12 },
];

// Helper: get demo user by role
export function getDemoUser(role: string): User {
  return demoUsers.find((u) => u.role === role) || demoUsers[0];
}

export function getDemoUserById(id: string): User | undefined {
  return demoUsers.find((u) => u.id === id);
}
